-- github.com is a shared Transport venue, not GitHub's editorial voice.
DELETE FROM publisher_host WHERE host = 'github.com' AND publisher_id IN (SELECT id FROM publisher WHERE slug = 'github');--> statement-breakpoint
-- Complete the registered API Sources without changing existing Source state.
INSERT INTO publisher (slug,name) VALUES
('simonwillison', 'Simon Willison'),
('react', 'React'),
('nextjs', 'Next.js'),
('typescript', 'TypeScript'),
('nodejs', 'Node.js'),
('rust', 'Rust'),
('svelte', 'Svelte'),
('astro', 'Astro'),
('deno', 'Deno'),
('bun', 'Bun'),
('rachelandrew', 'Rachel Andrew'),
('chriscoyier', 'Chris Coyier'),
('adactio', 'Jeremy Keith'),
('kentcdodds', 'Kent C. Dodds'),
('juliaevans', 'Julia Evans'),
('glyph', 'Glyph'),
('emollick', 'Ethan Mollick'),
('una', 'Una Kravets'),
('cassidoo', 'Cassidy Williams'),
('hn', 'Hacker News'),
('danluu', 'Dan Luu'),
('danabramov', 'Dan Abramov'),
('sophiebits', 'Sophie Alpert'),
('hynek', 'Hynek Schlawack'),
('crawshaw', 'David Crawshaw'),
('wesbos', 'Wes Bos'),
('bradfitz', 'Brad Fitzpatrick'),
('antirez', 'Salvatore Sanfilippo')
ON CONFLICT (slug) DO NOTHING;--> statement-breakpoint
INSERT INTO publisher_host (host,publisher_id) SELECT r.host,p.id FROM (VALUES
('simonwillison.net', 'simonwillison'),
('react.dev', 'react'),
('nextjs.org', 'nextjs'),
('devblogs.microsoft.com', 'typescript'),
('typescriptlang.org', 'typescript'),
('nodejs.org', 'nodejs'),
('blog.rust-lang.org', 'rust'),
('rust-lang.org', 'rust'),
('svelte.dev', 'svelte'),
('astro.build', 'astro'),
('deno.com', 'deno'),
('deno.land', 'deno'),
('bun.com', 'bun'),
('bun.sh', 'bun'),
('rachelandrew.co.uk', 'rachelandrew'),
('chriscoyier.net', 'chriscoyier'),
('css-tricks.com', 'chriscoyier'),
('adactio.com', 'adactio'),
('kentcdodds.com', 'kentcdodds'),
('jvns.ca', 'juliaevans'),
('glyph.im', 'glyph'),
('oneusefulthing.org', 'emollick'),
('una.im', 'una'),
('cassidoo.co', 'cassidoo'),
('news.ycombinator.com', 'hn'),
('danluu.com', 'danluu'),
('overreacted.io', 'danabramov'),
('sophiebits.com', 'sophiebits'),
('hynek.me', 'hynek'),
('crawshaw.io', 'crawshaw'),
('wesbos.com', 'wesbos'),
('bradfitz.com', 'bradfitz'),
('antirez.com', 'antirez')) AS r(host,slug) JOIN publisher p ON p.slug=r.slug
ON CONFLICT (host) DO NOTHING;--> statement-breakpoint
INSERT INTO source (publisher_id,transport,endpoint_url,is_aggregator) SELECT p.id,r.transport::source_transport,r.url,false FROM (VALUES
('simonwillison', 'bluesky_feed', 'https://public.api.bsky.app/xrpc/app.bsky.feed.getAuthorFeed?actor=did%3Aplc%3Akft6lu4trxowqmter2b6vg6z&limit=100&filter=posts_no_replies&includePins=false'),
('react', 'github_graphql', 'https://github.com/facebook/react/releases'),
('nextjs', 'github_graphql', 'https://github.com/vercel/next.js/releases'),
('typescript', 'github_graphql', 'https://github.com/microsoft/TypeScript/releases'),
('nodejs', 'github_graphql', 'https://github.com/nodejs/node/releases'),
('rust', 'github_graphql', 'https://github.com/rust-lang/rust/releases'),
('svelte', 'github_graphql', 'https://github.com/sveltejs/svelte/releases'),
('astro', 'github_graphql', 'https://github.com/withastro/astro/releases'),
('deno', 'github_graphql', 'https://github.com/denoland/deno/releases'),
('bun', 'github_graphql', 'https://github.com/oven-sh/bun/releases'),
('rachelandrew', 'bluesky_feed', 'https://public.api.bsky.app/xrpc/app.bsky.feed.getAuthorFeed?actor=did%3Aplc%3Axi53lkcvx4b3bl5tgsb7tnqe&limit=100&filter=posts_no_replies&includePins=false'),
('chriscoyier', 'bluesky_feed', 'https://public.api.bsky.app/xrpc/app.bsky.feed.getAuthorFeed?actor=did%3Aplc%3Axhhcrzsilpamjmz4dvrpt7df&limit=100&filter=posts_no_replies&includePins=false'),
('adactio', 'bluesky_feed', 'https://public.api.bsky.app/xrpc/app.bsky.feed.getAuthorFeed?actor=did%3Aplc%3Ar4p4qrbwfv7fbvpem5hjdmvl&limit=100&filter=posts_no_replies&includePins=false'),
('kentcdodds', 'bluesky_feed', 'https://public.api.bsky.app/xrpc/app.bsky.feed.getAuthorFeed?actor=did%3Aplc%3Axzefkiajzjmmyp6zq6ftczg3&limit=100&filter=posts_no_replies&includePins=false'),
('juliaevans', 'bluesky_feed', 'https://public.api.bsky.app/xrpc/app.bsky.feed.getAuthorFeed?actor=did%3Aplc%3Anzrozayxq764zbgl4qtp5ald&limit=100&filter=posts_no_replies&includePins=false'),
('glyph', 'bluesky_feed', 'https://public.api.bsky.app/xrpc/app.bsky.feed.getAuthorFeed?actor=did%3Aplc%3Avaa5e4jzfpx6znz3jzxqixym&limit=100&filter=posts_no_replies&includePins=false'),
('emollick', 'bluesky_feed', 'https://public.api.bsky.app/xrpc/app.bsky.feed.getAuthorFeed?actor=did%3Aplc%3Aflxq4uyjfotciovpw3x3fxnu&limit=100&filter=posts_no_replies&includePins=false'),
('una', 'bluesky_feed', 'https://public.api.bsky.app/xrpc/app.bsky.feed.getAuthorFeed?actor=did%3Aplc%3Akesmfbtx2loscqj7ktw5shtt&limit=100&filter=posts_no_replies&includePins=false'),
('cassidoo', 'bluesky_feed', 'https://public.api.bsky.app/xrpc/app.bsky.feed.getAuthorFeed?actor=did%3Aplc%3Abhdap3w2bseikypfnjmaskzf&limit=100&filter=posts_no_replies&includePins=false'),
('hn', 'hn_firebase', 'https://hacker-news.firebaseio.com/v0/topstories.json'),
('hn', 'hn_firebase', 'https://hacker-news.firebaseio.com/v0/newstories.json'),
('danluu', 'bluesky_feed', 'https://public.api.bsky.app/xrpc/app.bsky.feed.getAuthorFeed?actor=did%3Aplc%3A2mrgzk6xlemfv6yugn644xxy&limit=100&filter=posts_no_replies&includePins=false'),
('danabramov', 'bluesky_feed', 'https://public.api.bsky.app/xrpc/app.bsky.feed.getAuthorFeed?actor=did%3Aplc%3Afpruhuo22xkm5o7ttr2ktxdo&limit=100&filter=posts_no_replies&includePins=false'),
('sophiebits', 'bluesky_feed', 'https://public.api.bsky.app/xrpc/app.bsky.feed.getAuthorFeed?actor=did%3Aplc%3Alq6wgt3qcyog37cw65o5c277&limit=100&filter=posts_no_replies&includePins=false'),
('hynek', 'bluesky_feed', 'https://public.api.bsky.app/xrpc/app.bsky.feed.getAuthorFeed?actor=did%3Aplc%3A6k63663icgdybm5evgszxjn2&limit=100&filter=posts_no_replies&includePins=false'),
('crawshaw', 'bluesky_feed', 'https://public.api.bsky.app/xrpc/app.bsky.feed.getAuthorFeed?actor=did%3Aplc%3Asbgmax2bfm5dlje36qwvzuuq&limit=100&filter=posts_no_replies&includePins=false'),
('wesbos', 'bluesky_feed', 'https://public.api.bsky.app/xrpc/app.bsky.feed.getAuthorFeed?actor=did%3Aplc%3Aetdjdgnly5tz5l5xdd4jq76d&limit=100&filter=posts_no_replies&includePins=false'),
('bradfitz', 'bluesky_feed', 'https://public.api.bsky.app/xrpc/app.bsky.feed.getAuthorFeed?actor=did%3Aplc%3A7r2fy3b4u7mmnhgbdxnflovv&limit=100&filter=posts_no_replies&includePins=false'),
('antirez', 'bluesky_feed', 'https://public.api.bsky.app/xrpc/app.bsky.feed.getAuthorFeed?actor=did%3Aplc%3Aipt7y6qaf6fn7oeeduboqe44&limit=100&filter=posts_no_replies&includePins=false')) AS r(slug,transport,url) JOIN publisher p ON p.slug=r.slug
ON CONFLICT (endpoint_url) DO NOTHING;
